export const GEO_URL = 'https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json'

// ISO Alpha-2 to Alpha-3 country code mapping (common countries)
const COUNTRY_CODE_MAP: Record<string, string> = {
  AF: 'AFG',
  AL: 'ALB',
  DZ: 'DZA',
  AD: 'AND',
  AO: 'AGO',
  AR: 'ARG',
  AM: 'ARM',
  AU: 'AUS',
  AT: 'AUT',
  AZ: 'AZE',
  BS: 'BHS',
  BH: 'BHR',
  BD: 'BGD',
  BY: 'BLR',
  BE: 'BEL',
  BZ: 'BLZ',
  BJ: 'BEN',
  BT: 'BTN',
  BO: 'BOL',
  BA: 'BIH',
  BW: 'BWA',
  BR: 'BRA',
  BN: 'BRN',
  BG: 'BGR',
  BF: 'BFA',
  BI: 'BDI',
  KH: 'KHM',
  CM: 'CMR',
  CA: 'CAN',
  CF: 'CAF',
  TD: 'TCD',
  CL: 'CHL',
  CN: 'CHN',
  CO: 'COL',
  CG: 'COG',
  CD: 'COD',
  CR: 'CRI',
  HR: 'HRV',
  CU: 'CUB',
  CY: 'CYP',
  CZ: 'CZE',
  DK: 'DNK',
  DJ: 'DJI',
  DO: 'DOM',
  EC: 'ECU',
  EG: 'EGY',
  SV: 'SLV',
  GQ: 'GNQ',
  ER: 'ERI',
  EE: 'EST',
  ET: 'ETH',
  FI: 'FIN',
  FR: 'FRA',
  GA: 'GAB',
  GM: 'GMB',
  GE: 'GEO',
  DE: 'DEU',
  GH: 'GHA',
  GR: 'GRC',
  GT: 'GTM',
  GN: 'GIN',
  GW: 'GNB',
  GY: 'GUY',
  HT: 'HTI',
  HN: 'HND',
  HU: 'HUN',
  IS: 'ISL',
  IN: 'IND',
  ID: 'IDN',
  IR: 'IRN',
  IQ: 'IRQ',
  IE: 'IRL',
  IL: 'ISR',
  IT: 'ITA',
  CI: 'CIV',
  JM: 'JAM',
  JP: 'JPN',
  JO: 'JOR',
  KZ: 'KAZ',
  KE: 'KEN',
  KP: 'PRK',
  KR: 'KOR',
  KW: 'KWT',
  KG: 'KGZ',
  LA: 'LAO',
  LV: 'LVA',
  LB: 'LBN',
  LS: 'LSO',
  LR: 'LBR',
  LY: 'LBY',
  LT: 'LTU',
  LU: 'LUX',
  MK: 'MKD',
  MG: 'MDG',
  MW: 'MWI',
  MY: 'MYS',
  ML: 'MLI',
  MR: 'MRT',
  MX: 'MEX',
  MD: 'MDA',
  MN: 'MNG',
  ME: 'MNE',
  MA: 'MAR',
  MZ: 'MOZ',
  MM: 'MMR',
  NA: 'NAM',
  NP: 'NPL',
  NL: 'NLD',
  NZ: 'NZL',
  NI: 'NIC',
  NE: 'NER',
  NG: 'NGA',
  NO: 'NOR',
  OM: 'OMN',
  PK: 'PAK',
  PA: 'PAN',
  PG: 'PNG',
  PY: 'PRY',
  PE: 'PER',
  PH: 'PHL',
  PL: 'POL',
  PT: 'PRT',
  QA: 'QAT',
  RO: 'ROU',
  RU: 'RUS',
  RW: 'RWA',
  SA: 'SAU',
  SN: 'SEN',
  RS: 'SRB',
  SL: 'SLE',
  SG: 'SGP',
  SK: 'SVK',
  SI: 'SVN',
  SO: 'SOM',
  ZA: 'ZAF',
  SS: 'SSD',
  ES: 'ESP',
  LK: 'LKA',
  SD: 'SDN',
  SR: 'SUR',
  SZ: 'SWZ',
  SE: 'SWE',
  CH: 'CHE',
  SY: 'SYR',
  TW: 'TWN',
  TJ: 'TJK',
  TZ: 'TZA',
  TH: 'THA',
  TL: 'TLS',
  TG: 'TGO',
  TN: 'TUN',
  TR: 'TUR',
  TM: 'TKM',
  UG: 'UGA',
  UA: 'UKR',
  AE: 'ARE',
  GB: 'GBR',
  US: 'USA',
  UY: 'URY',
  UZ: 'UZB',
  VE: 'VEN',
  VN: 'VNM',
  YE: 'YEM',
  ZM: 'ZMB',
  ZW: 'ZWE',
  HK: 'HKG',
  MO: 'MAC',
}

// Country names mapping for tooltip display
const COUNTRY_NAMES: Record<string, string> = {
  MY: 'Malaysia',
  SG: 'Singapore',
  US: 'United States',
  GB: 'United Kingdom',
  IN: 'India',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  AU: 'Australia',
  DE: 'Germany',
  FR: 'France',
  IT: 'Italy',
  ES: 'Spain',
  NL: 'Netherlands',
  CA: 'Canada',
  BR: 'Brazil',
  MX: 'Mexico',
  ID: 'Indonesia',
  TH: 'Thailand',
  VN: 'Vietnam',
  PH: 'Philippines',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  RU: 'Russia',
  UA: 'Ukraine',
  PL: 'Poland',
  TR: 'Turkey',
  SA: 'Saudi Arabia',
  AE: 'UAE',
  EG: 'Egypt',
  ZA: 'South Africa',
  NG: 'Nigeria',
  KE: 'Kenya',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
  HK: 'Hong Kong',
}

// Numeric ISO code to Alpha-2 mapping
const NUMERIC_TO_ALPHA2: Record<string, string> = {
  '458': 'MY',
  '702': 'SG',
  '840': 'US',
  '826': 'GB',
  '356': 'IN',
  '156': 'CN',
  '392': 'JP',
  '410': 'KR',
  '036': 'AU',
  '276': 'DE',
  '250': 'FR',
  '380': 'IT',
  '724': 'ES',
  '528': 'NL',
  '124': 'CA',
  '076': 'BR',
  '484': 'MX',
  '360': 'ID',
  '764': 'TH',
  '704': 'VN',
  '608': 'PH',
  '586': 'PK',
  '050': 'BD',
  '643': 'RU',
  '804': 'UA',
  '616': 'PL',
  '792': 'TR',
  '682': 'SA',
  '784': 'AE',
  '818': 'EG',
  '710': 'ZA',
  '566': 'NG',
  '404': 'KE',
  '032': 'AR',
  '152': 'CL',
  '170': 'CO',
  '604': 'PE',
  '344': 'HK',
  '446': 'MO',
}

// Convert country code to Alpha-2
export function toAlpha2(code: string | undefined | null): string | null {
  if (!code) return null
  // Already Alpha-2
  if (code.length === 2 && COUNTRY_CODE_MAP[code]) return code
  // Alpha-3 to Alpha-2
  const fromAlpha3 = Object.entries(COUNTRY_CODE_MAP).find(
    ([, alpha3]) => alpha3 === code,
  )?.[0]
  if (fromAlpha3) return fromAlpha3
  // Numeric to Alpha-2
  return NUMERIC_TO_ALPHA2[code] || null
}

// Get country display name from Alpha-2 code
export function getCountryName(alpha2: string): string {
  return COUNTRY_NAMES[alpha2] || alpha2
}
